<?php

return array(
	'' => __( 'None', 'siteorigin-premium' ),
	'bounce' => 'bounce',
	'flash' => 'flash',
	'pulse' => 'pulse',
	'rubberBand' => 'rubberBand',
	'shake' => 'shake',
	'swing' => 'swing',
	'tada' => 'tada',
	'wobble' => 'wobble',
	'jello' => 'jello',
	'bounceIn' => 'bounceIn',
	'bounceInDown' => 'bounceInDown',
	'bounceInLeft' => 'bounceInLeft',
	'bounceInRight' => 'bounceInRight',
	'bounceInUp' => 'bounceInUp',
	'fadeIn' => 'fadeIn',
	'fadeInDown' => 'fadeInDown',
	'fadeInDownBig' => 'fadeInDownBig',
	'fadeInLeft' => 'fadeInLeft',
	'fadeInLeftBig' => 'fadeInLeftBig',
	'fadeInRight' => 'fadeInRight',
	'fadeInRightBig' => 'fadeInRightBig',
	'fadeInUp' => 'fadeInUp',
	'fadeInUpBig' => 'fadeInUpBig',
	'flip' => 'flip',
	'flipInX' => 'flipInX',
	'flipInY' => 'flipInY',
	'lightSpeedIn' => 'lightSpeedIn',
	'rotateIn' => 'rotateIn',
	'rotateInDownLeft' => 'rotateInDownLeft',
	'rotateInDownRight' => 'rotateInDownRight',
	'rotateInUpLeft' => 'rotateInUpLeft',
	'rotateInUpRight' => 'rotateInUpRight',
	'slideInUp' => 'slideInUp',
	'slideInDown' => 'slideInDown',
	'slideInLeft' => 'slideInLeft',
	'slideInRight' => 'slideInRight',
	'zoomIn' => 'zoomIn',
	'zoomInDown' => 'zoomInDown',
	'zoomInLeft' => 'zoomInLeft',
	'zoomInRight' => 'zoomInRight',
	'zoomInUp' => 'zoomInUp',
	'hinge' => 'hinge',
	'rollIn' => 'rollIn',
);